# Generated by Django 5.2.3 on 2025-06-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nganya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nganya.route'),
        ),
    ]
